name: Dev dockerize, push images to hub and deploy to Heroku

on:
  push:
    branches: [dev]

jobs:
  dockerize-and-push-to-hub:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push InventoryManagement
        uses: docker/build-push-action@v2
        with:
          context: InventoryManagement/.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inventory-management:dev
      - name: Build and push Ordering
        uses: docker/build-push-action@v2
        with:
          context: Ordering/.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ordering:dev
      - name: Build and push Reporting
        uses: docker/build-push-action@v2
        with:
          context: Reporting/.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/reporting:dev
      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: frontend/.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webstore-frontend:dev
      - name: Destroy previously Heroku deployed apps
        run: ./stop-terraform-dev.sh ${{ secrets.HEROKU_DEV_EMAIL }} ${{ secrets.HEROKU_DEV_ACCESS_TOKEN }} ${{ secrets.TERRAFORM_DEV_BACKEND_NAME }}
        shell: bash
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - name: Deploy apps to Heroku
        run: ./start-terraform-dev.sh ${{ secrets.HEROKU_DEV_EMAIL }} ${{ secrets.HEROKU_DEV_ACCESS_TOKEN }} ${{ secrets.TERRAFORM_DEV_BACKEND_NAME }}
        shell: bash
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
